swagger: '2.0'
info:
  title: 'Swagger'
  description: >
    This is Hall of fame Koa API.
  version: '1.0.0'
host: 'localhost:7654'
schemes:
  - 'http'

paths:
  /students:
    get:
      summary: 'Get all sudents'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'successful operation'
          schema:
            type: 'array'
            items: { $ref: '#/definitions/Student' }
        500:
          $ref: '#/responses/500'
    post:
      summary: 'Add new student'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Student object that needs to be added'
          requiered: true
          schema: { $ref: '#/definitions/Student' }
      responses:
        201:
          description: 'successful operation'
          schema: { $ref: '#/definitions/Student' }
        500:
          $ref: '#/responses/500'
  /students/{id}:
    put:
      summary: 'Update student with given ID'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: 'id'
          description: 'ID of Student that needs to be updated'
          requiered: true
          type: integer
          format: int64
        - in: 'body'
          name: 'body'
          description: 'Student object that needs to be added'
          requiered: true
          schema: { $ref: '#/definitions/Student' }
      responses:
        201:
          description: 'successful operation'
          schema: { $ref: '#/definitions/Student' }
        400:
          description: 'Invalid ID supplied'
        500:
          $ref: '#/responses/500'
    delete:
      summary: 'Delete student with given ID'
      parameters:
        - in: 'path'
          name: 'id'
          description: 'ID of Student that needs to be deleted'
          requiered: true
          type: integer
          format: int64
      responses:
        204:
          description: 'successful operation'
        400:
          description: 'Invalid ID supplied'
        500:
          $ref: '#/responses/500'

responses:
  500:
    description: Internal Server Error

definitions:
  Student:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
        example: 'Test'
      birthdate:
        type: 'string'
        format: 'date-time'
        example: '2000-01-01'
      grade:
        type: 'string'
        enum: ['неуд', 'уд', 'хор', 'отл']
        example: 'отл'
